### ISSUE TITLE
やることを箇条書きし、issueを作成する

### ISSUE THREAD

**Issue by HattoriNaoki-t** [HattoriNaoki-t/git_tutorial#15]
issueを立てる流れから解決までの流れを説明

**Comment by sekaizyu** [comment]
![5](https://cloud.githubusercontent.com/assets/15883766/25264825/6eaf8094-26a4-11e7-9342-c6dc0a5e8007.PNG)

**Comment by HattoriNaoki-t** [comment]
![5](https://cloud.githubusercontent.com/assets/15883766/25264848/a7a32f86-26a4-11e7-9995-754a1a73b6a1.PNG)

**Comment by sekaizyu** [comment]
![10](https://cloud.githubusercontent.com/assets/15883766/25265706/4437734e-26a9-11e7-95c0-8a7118f3eb40.PNG)

**Comment by HattoriNaoki-t** [comment]
New issueをクリック

**Comment by HattoriNaoki-t** [comment]
![10](https://cloud.githubusercontent.com/assets/15883766/25265721/5a8673e8-26a9-11e7-94f6-3cfc8b26b997.PNG)

**Comment by HattoriNaoki-t** [comment]
するとこのような画面になるので
![11](https://cloud.githubusercontent.com/assets/15883766/25265748/734c724c-26a9-11e7-944a-6104e103ea30.PNG)

**Comment by sekaizyu** [comment]
![11](https://cloud.githubusercontent.com/assets/15883766/25265748/734c724c-26a9-11e7-944a-6104e103ea30.PNG)

**Comment by HattoriNaoki-t** [comment]
最初に極力切り分けた目標を描いたissueを立てる
例　Playerの移動を作成,ステージの作成,エネミーを作成

**Comment by HattoriNaoki-t** [comment]
するとissue画面にその項目が追加される
![13](https://cloud.githubusercontent.com/assets/15883766/25265948/5fa2495a-26aa-11e7-8e0a-aac70b4541f2.PNG)

**Comment by sekaizyu** [comment]
![12](https://cloud.githubusercontent.com/assets/15883766/25265906/1fd0bf32-26aa-11e7-84c0-6007c7231ac8.PNG)

**Comment by sekaizyu** [comment]
![13](https://cloud.githubusercontent.com/assets/15883766/25265948/5fa2495a-26aa-11e7-8e0a-aac70b4541f2.PNG)

**Comment by HattoriNaoki-t** [comment]
項目をクリックして
そのissueを完成させるためにissueを立てる
そのissueを立てる理由はコメントを書いて記入しておくとわかりやすい。

**Comment by sekaizyu** [comment]
![14](https://cloud.githubusercontent.com/assets/15883766/25266034/a05498ae-26aa-11e7-9769-8a42297b2982.PNG)

**Comment by sekaizyu** [comment]
以上でissueを立てる方法と
実際の使い方の説明を終了する

**Comment by HattoriNaoki-t** [comment]
4/28 右枠の説明が不足していたことに気づきその部分の補足説明を入れる

**Comment by HattoriNaoki-t** [comment]
![15](https://cloud.githubusercontent.com/assets/15883766/25510548/df4801bc-2bfb-11e7-8ffb-6ab563691be2.PNG)

**Comment by HattoriNaoki-t** [comment]
まずAssignees(アサイニー)　直訳で代理人
複数人で作品を制作する際に仕事を割り振った人を明確にする（主にタスクリーダ）
依頼者を明確にすることにより使用で困ったときなどに誰に相談するのかなどが一目でわかる

**Comment by HattoriNaoki-t** [comment]
![15](https://cloud.githubusercontent.com/assets/15883766/25510648/bb41614a-2bfc-11e7-8c6a-97fc0f91fc01.PNG)

**Comment by HattoriNaoki-t** [comment]
![16](https://cloud.githubusercontent.com/assets/15883766/25510709/27b4f4fe-2bfd-11e7-9df8-c161945ac564.PNG)

**Comment by HattoriNaoki-t** [comment]
次はLabels（ラベル）　
標準で用意しているものは
bug	バグ。修正したらクローズ。
duplicate	他のイシューと重複している。重複先のイシューにリンクしてクローズ
enhancement	機能追加。実装したらクローズ。
help wanted	助けが必要。解決したらクローズ。
invalid	間違い、勘違い、実現不可能。対応しない理由を書いてクローズ。
question	質問、議論。収束したらクローズ。
wontfix	分かっちゃいるけど対応しないバグ。対応しない理由を書いてクローズ。

**Comment by HattoriNaoki-t** [comment]
これは自由に追加でき、
プロジェクト担当者であればラベルを作成出来る。
作成する場所のＵＲＬは
https://github.com/ユーザ名/指定リポジトリ/labels
このリポジトリであれば
https://github.com/HattoriNaoki-t/git_study/labels
にアクセスすれば編集できる

**Comment by HattoriNaoki-t** [comment]
![17](https://cloud.githubusercontent.com/assets/15883766/25510852/10e6c3fa-2bfe-11e7-8bd2-0a1395ae4e06.PNG)

**Comment by HattoriNaoki-t** [comment]
New labelを押し
追加したいラベルを書きそのラベルの色を選択して追加する
（色は緊急度は赤　追加要素は黄色など個人又はチームで決める
私自身が追加したものとして例も挙げておく（例: In Progress 現在作業中 Ready: 作業待機中）
作業を始めるときに作業中に変更することにより、
ラベルを付け替えた瞬間にissueに通知されるので誰がどこで何をやり始めたかがわかる。

**Comment by HattoriNaoki-t** [comment]
![17](https://cloud.githubusercontent.com/assets/15883766/25511551/62dd0ac6-2c02-11e7-84f3-9651d0a16743.PNG)

**Comment by HattoriNaoki-t** [comment]
![16](https://cloud.githubusercontent.com/assets/15883766/25511556/69611c02-2c02-11e7-9a7f-41448fc8abdb.PNG)

**Comment by HattoriNaoki-t** [comment]
![15](https://cloud.githubusercontent.com/assets/15883766/25511750/c8e157f4-2c03-11e7-9c5d-946d54d6607c.PNG)

**Comment by HattoriNaoki-t** [comment]
次はProjects 
こちらは後ほどProjectタブを説明する際に深く説明するので、
軽く説明するとこちらでプロジェクトを選択しておくと、
Projecタブで状態を見やすく表示させる事が出来る。
詳細issue : #19

**Comment by HattoriNaoki-t** [comment]
![15](https://cloud.githubusercontent.com/assets/15883766/25512352/03138aba-2c08-11e7-8d36-a623923991ad.PNG)

**Comment by HattoriNaoki-t** [comment]
最後はMilestone(マイルストーン)
バージョンアップをする際のスケジュールを書く場所で、
タイトル、アップデートすること、期限を設定できる

**Comment by HattoriNaoki-t** [comment]
以上で改めてissueの説明を終わらせる

**Comment by HattoriNaoki-t** [comment]
## 新しく追加された項目！

Notifications
  Unsubscribe
通知をもらうか否か
![23](https://user-images.githubusercontent.com/15883766/29950940-44301810-8efa-11e7-878f-6c350893e08b.PNG)
