### ISSUE TITLE
Wikiを記入する

### ISSUE THREAD

**Issue by HattoriNaoki-t** [HattoriNaoki-t/git_tutorial#16]
#1 
Wikiの書き方の参考例を作成する

**Comment by HattoriNaoki-t** [comment]
![default](https://cloud.githubusercontent.com/assets/15883766/25265305/4c1d9248-26a7-11e7-920a-cff19e1d8a06.PNG)

**Comment by HattoriNaoki-t** [comment]
するとこのような画面が出るのでEditをクリック

**Comment by HattoriNaoki-t** [comment]
![default](https://cloud.githubusercontent.com/assets/15883766/25265320/635c631c-26a7-11e7-9b53-ca3f9b189976.PNG)

**Comment by HattoriNaoki-t** [comment]
参考例↓
改行は一度は改行として認識されないので二回打つ。

**Comment by sekaizyu** [comment]
![8](https://cloud.githubusercontent.com/assets/15883766/25265411/dc0c07e0-26a7-11e7-8f3f-afb20006e6f2.PNG)

**Comment by HattoriNaoki-t** [comment]
![default](https://cloud.githubusercontent.com/assets/15883766/25265428/feb3a14a-26a7-11e7-9a55-a9e0e8903815.PNG)

**Comment by HattoriNaoki-t** [comment]
Saveをすると実際にこのような画面になる

**Comment by HattoriNaoki-t** [comment]
![default](https://cloud.githubusercontent.com/assets/15883766/25265637/fa5b9da4-26a8-11e7-8458-748488dfbce4.PNG)
