### ISSUE TITLE
githubのタブの事について説明

### ISSUE THREAD

**Issue by HattoriNaoki-t** [HattoriNaoki-t/git_tutorial#6]
#1 
タブの説明
(code,issue,pull requests,projects,wiki,graphs,settings)
写真も付与

**Comment by sekaizyu** [comment]
![default](https://cloud.githubusercontent.com/assets/15883766/25259168/837f03b6-267f-11e7-820c-4f6c71c692cb.PNG)

**Comment by HattoriNaoki-t** [comment]
![default](https://cloud.githubusercontent.com/assets/15883766/25259188/9ff31fa0-267f-11e7-8056-f35149618034.PNG)

**Comment by HattoriNaoki-t** [comment]
左から説明

Code:作成した作品のコード全てが表示されている

issues: 直訳で問題。
 そのまま現在作品を完成にあたって必要なものを細かく提示、
 それによって起こった問題点などを提示する場所。

PullRequests:本番環境に統合するにあたって、
 管理者・共同者などに確認を必須かすることによって品質を向上させるための機能。

Projets:色々な作業状態（作業中、作業停止中、次にやること）などの状態を
 一目で管理、編集できるもの(Trelloやwaffieになどの機能と同一

Wiki:制作概念や関わりのあるもの割と幅広く書きたい事をかける場所。特に厳しい制約などはないので、
 自由に。

Pules:誰がどのくらい全体に貢献していて、どの作業が終わったかなどを明確に表示する

Graphs:コミットの数や追加・削除されたコードの量などをグラフで確認できます。
 Pulseタブ同様、リポジトリの活動状況を把握するために役立つ。

settings:現在のリポジトリの設定項目。名前の変更などが出来る。
